#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2025.3.2.2"

# Which optional robotpy components should be installed?
# -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = [
    #"all",
    # "apriltag",
    # "commands2",
    # "cscore",
    # "romi",
    # "sim",
    # "xrp",
    "rev",
]

# Other pip packages to install, such as vendor packages (each element
# is equivalent to a line in requirements.txt)
requires = []

[tool.pyright]
typeCheckingMode = "standard"
